import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const defaultEndpoint = `https://jsonplaceholder.typicode.com/users`;

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {
  // const { results = []} = data;
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Project API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sample API Project
        </h1>

        <p className={styles.description}>
          Ajay Jose A
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <ul className={styles.grid}>
          {data.map(data => {
            const { id , name } = data;

            return (
              <li key={id} className={styles.card}>
                <Link legacyBehavior href="/user/[userId]" as={`/user/${id}`}>
                  <a>
                    <h2>{ name }</h2>
                  </a>
                </Link>
              </li>
            )
          })} 
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
