import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react';

const defaultEndpoint = `https://jsonplaceholder.typicode.com/users`;

// export async function getServerSideProps() {
//   const res = await fetch(defaultEndpoint)
//   const data = await res.json();
//   return {
//     props: {
//       data
//     }
//   }
// }

export default function Home() {
  const [names, setNames] = useState([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState("");
  const [filterValue, setFilterValue] = useState([]);
 
  
  useEffect(() => {
    setLoading(true);
    fetch(`${defaultEndpoint}`)
      .then((res) => res.json())
      .then((data) => {
          setNames(data);
          setLoading(false);
      })
  }, []);
 
  
  useEffect(() => {
      setFilterValue(
        names.filter((user) =>
          user.name.toLowerCase().includes(search.toLowerCase())
        )
      );
  }, [search, names]);
  
  if (loading) {
      return <div>Loading...</div>;
  }
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          User Details API
        </h1>

        <form className={styles.search} >
          <input placeholder='Search' onChange={(e) => setSearch(e.target.value)}/>
          <button className={styles.searchbutton}>Search</button>
        </form>

        <ul className={styles.grid}>
          {filterValue.map(data => {
            const { id , name } = data;

            return (
              <li key={id} className={styles.card}>
                <Link legacyBehavior href="/user/[userId]" as={`/user/${id}`}>
                  <a>
                    <h2>{ name }</h2>
                  </a>
                </Link>
              </li>
            )
          })} 
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
